#!/usr/bin/env ruby
require 'rubygems'
require 'commander'
require 'parallel'
require 'net/http'
require 'mathnet/crawler'
require 'exponential_backoff'

class MyApplication
  include Commander::Methods

  def run
    program :name, 'Mathnet crawler.'
    program :version, '1.0.0'
    program :description, 'Stupid command that prints foo or bar.'

    command :'download all' do |c|
      c.syntax = 'download all'
      c.description = 'Download all articals'
      c.action do |args, options|
        journals = list_journals
        issues = list_issues journals
        articals = list_articals issues
        say articals.size
      end
    end

    run!
  end

  def list_journals
    say 'List all journals...'
    process_backoff do 
      Mathnet::Crawler::Journal.list Mathnet::Crawler::Library.new
    end
  end

  def list_issues(journals)
    issues_lists = Parallel.map(journals, :progress => 'List issues') do |journal|
      process_backoff do 
        Mathnet::Crawler::Issue.list journal
      end
    end
    issues_lists.compact.reduce do |initial, item|
      initial + item
    end
  end

  def list_articals(issues)
    articals_lists = Parallel.map(issues, :progress => 'List articals') do |issue| 
      process_backoff do 
        Mathnet::Crawler::Article.list issue
      end
    end
    articals_lists.compact.reduce do |initial, item|
      initial + item
    end
  end

  def process_backoff(&block)
    backoff.until_success do
      begin
        result = block
      rescue Net::HTTPServerException
        result = false 
      end
      return result
    end
  end

  def backoff
    minimal_interval = 0.1
    maximal_elapsed_time = 10.0
    ExponentialBackoff.new(minimal_interval, maximal_elapsed_time)
  end
end

MyApplication.new.run if $PROGRAM_NAME == __FILE__
